F08
duftor/crazee-burger pull request #8
Opened 2023-03-14 11:45 UTC by duftor

2023-03-14 12:31 UTC, vileaddev requested changes
Très bien ! Quelques changements à voir :)

2023-03-14 12:31 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AddProductForm.js
> +	const handleNameChange = (e) => {
peut mieux faire ici, je t'expliquerai pendant le live

2023-03-14 12:31 UTC, vileaddev commented on src/components/pages/order/Main/EmptyMenuPage.js
> +			<form onSubmit={handleSubmit}>
un bouton d'action n'est pas forcément dans un form. Un form c'est pour collecter des données du user, ici on ne le fait pas donc une simple div aurait suffit et donc un simple onClick aussi

2023-03-14 12:31 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +	const menuContext = {
pourquoi créer deux context différents s'ils sont positionné au même niveau dans l'arbre ?

2023-03-14 12:31 UTC, vileaddev commented on src/components/pages/order/Main/Menu.js
> +							imageSource={imageSource ? imageSource : comingSoonImageUrl}
Oui, très bien ! 💯

2023-03-14 12:31 UTC, vileaddev commented on src/components/pages/order/Main/Menu.js
> +							imageSource={imageSource ? imageSource : comingSoonImageUrl}
```suggestion
							imageSource={imageSource ? imageSource : defaultImage}
```

Tu peux aller encore plus loin et donner un nom explicite à ta variable

2023-03-14 12:31 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +	isThereRemoveButton,
```suggestion
	hasDeleteButton,
```

2023-03-14 12:31 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +						color="#ffa01b"
```suggestion
						
```

si tu as déjà le className, autant ajouter le color là bas

+ utiliser le design system (theme.index)

2023-03-14 12:31 UTC, vileaddev commented on src/context/MenuContext.js
> +export default createContext({
pas certain que créer un Context à part apporte quelque chose en plus ici

2023-03-14 12:31 UTC, vileaddev commented on src/theme/index.js
> +	family: {
smart ! 🧠 J'approve 💯

2023-03-14 12:31 UTC, vileaddev commented on src/utils/maths.js
> +	var prixSansEspace = chaine.replace(/\s/g, "") // Supprimer les espaces
tu peux remplacer tous les var par des let

2023-03-14 12:43 UTC, duftor commented on src/components/pages/order/Main/Main.js
> +	const menuContext = {
C'était pour bien dissocier l'admin context du menu context

2023-03-14 13:17 UTC, vileaddev requested changes
Très très bien ! 😃

2023-03-14 13:17 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AddProductForm.js
> +		<AddProductFormStyled imageUrl={imageUrl}>
Pas hyper fan de split la logique d'affichage entre JSX et Styled Component 😕  Il existe d'autres manières de faire sans

2023-03-14 13:17 UTC, vileaddev commented on src/components/pages/order/Main/EmptyMenuPage.js
> +			<PrimaryButton
YES ! 💯

2023-03-14 13:17 UTC, vileaddev commented on src/components/pages/order/Main/Menu.js
> +							imageSource={imageSource ? imageSource : defaultImage}
YES ! 💯

2023-03-21 18:04 UTC, vileaddev approved these changes
Dans l'ensemble, je valide. Quelques commentaires cela dit mais je valide ✅

2023-03-21 18:04 UTC, vileaddev commented on src/components/pages/order/Main/MainRightSide/Admin/tabsConfig.js
> +		content: <AddForm />,
```suggestion
		Content: <AddForm />,
```

2023-03-21 18:04 UTC, vileaddev commented on src/components/pages/order/Main/MainRightSide/Admin/tabsConfig.js
> +		content: "",
```suggestion
		Content: "",
```

2023-03-21 18:04 UTC, vileaddev commented on src/components/pages/order/Main/MainRightSide/Admin/AdminPanel/AdminPanel.js
> +	return <AdminPanelStyled>{tabSelectedInfo.content}</AdminPanelStyled>
```suggestion
	return <AdminPanelStyled>{tabSelectedInfo.content}</AdminPanelStyled>
```
```suggestion
	return <AdminPanelStyled>{tabSelectedInfo.Content}</AdminPanelStyled>
```

2023-03-21 18:04 UTC, vileaddev commented on src/components/pages/order/Main/MainRightSide/Admin/AdminPanel/ImagePreview.js
> +				<img src={imageSource} alt="" />
**_Rigoureusement_, on devrait faire ça :** 

```suggestion
				<img src={imageSource} alt={title} />
```
le title pourrait venir des props ?

2023-03-21 18:04 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +		let priceFormated = convertToNumber(productToAdd.price)
Pour information, en vrai, tu n'es pas obligé de gérer ce cas là puisque j'ai changé les règles métier. Donc au choix, tu peux garder ça ou le retirer ✅

2023-03-21 21:40 UTC, merged